name: C++ CMake CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Test
        # Реализация классического цикла сборки: mkdir, cd, cmake, make
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./text
